sudo: false

os:
 - linux

language: d

d:
 - dmd
 - ldc
 - ldc-beta

matrix:
  allow_failures:
    - {d: ldc-beta}

branches:
  only:
    - master

script:
 - dub test -c unittest-blas
#  - if [ "$DC" = "ldc2" ]; then rm -rf .dub && dub build -c blas --compiler=ldmd2 --build-mode=singleFile --build=better-c-release --force && g++ -std=c++1y -pthread -I./include examples/least_squares.cpp -L./ -lmir-optim -llapack -lblas && ./a.out; fi
#  - meson build -D with_test=true && cd build && ninja -j4 && ninja test -v && cd ..

addons:
  apt:
    update: true
    packages:
     - liblapack-dev
     - pkg-config

# install:
#   - pyenv global system 3.6
#   - pip3 install 'meson>=0.45'
#   - mkdir .ntmp
#   - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
#   - unzip .ntmp/ninja-linux.zip -d .ntmp
# before_script:
#   - export PATH=$PATH:$PWD/.ntmp

